import type { Patient, Zone, Alert, ActivityEvent } from "./types"

export const demoPatient: Patient = {
  id: "1",
  firstName: "Eleanor",
  lastName: "Rigby",
  photo: "/placeholder.svg?height=120&width=120",
  dateOfBirth: "1946-01-12",
  height: "5'4\"",
  weight: "130 lbs",
  eyeColor: "Blue",
  hairColor: "Silver/Gray",
  distinguishingFeatures: "Silver bracelet on left wrist, small scar on forehead",
  diagnosis: "Alzheimer's Disease",
  conditions: ["Alzheimer's", "Hypertension", "Arthritis"],
  medications: [
    { name: "Donepezil", dosage: "10mg", frequency: "Nightly" },
    { name: "Lisinopril", dosage: "5mg", frequency: "Morning" },
    { name: "Acetaminophen", dosage: "500mg", frequency: "As needed" },
  ],
  allergies: ["Penicillin (Severe)"],
  bloodType: "O+",
  wanderingTriggers: [
    "Sundowning (late afternoon)",
    "Looking for deceased spouse",
    "Searching for childhood home",
    "Restlessness after meals",
  ],
  calmingStrategies: [
    "Play classical music (Mozart preferred)",
    "Show family photo album",
    "Offer warm tea with honey",
    "Gentle hand massage",
  ],
  communicationAbility: "limited",
  mobilityLevel: "medium",
  device: {
    id: "SW-9928-XA",
    name: "SafeWander Pro Band",
    batteryLevel: 84,
    signalStrength: "strong",
    lastUpdate: new Date().toISOString(),
  },
  currentPosition: { lat: 37.7749, lng: -122.4194 },
  currentZone: "home",
  status: "safe",
  emergencyContacts: [
    {
      id: "1",
      name: "Jane Doe",
      relationship: "Daughter",
      phone: "(555) 123-4567",
      isPrimary: true,
    },
    {
      id: "2",
      name: "Dr. Emily Chen",
      relationship: "Primary Physician",
      phone: "(555) 987-6543",
      isPrimary: false,
    },
    {
      id: "3",
      name: "Robert Rigby",
      relationship: "Son",
      phone: "(555) 456-7890",
      isPrimary: false,
    },
  ],
}

export const demoZones: Zone[] = [
  {
    id: "home",
    patientId: "1",
    name: "Home Perimeter",
    type: "safe",
    shape: "circle",
    center: { lat: 37.7749, lng: -122.4194 },
    radius: 50,
    isActive: true,
    color: "#10b981",
  },
  {
    id: "backyard",
    patientId: "1",
    name: "Backyard",
    type: "safe",
    shape: "circle",
    center: { lat: 37.7747, lng: -122.419 },
    radius: 25,
    isActive: true,
    color: "#10b981",
  },
  {
    id: "park",
    patientId: "1",
    name: "Oakwood Park",
    type: "routine",
    shape: "circle",
    center: { lat: 37.776, lng: -122.418 },
    radius: 100,
    isActive: true,
    color: "#8b5cf6",
  },
  {
    id: "main-road",
    patientId: "1",
    name: "Main Road",
    type: "danger",
    shape: "circle",
    center: { lat: 37.777, lng: -122.417 },
    radius: 30,
    isActive: true,
    color: "#ef4444",
  },
]

export const demoAlerts: Alert[] = [
  {
    id: "9923",
    patientId: "1",
    type: "door_open",
    severity: "critical",
    status: "active",
    title: "Door Opened",
    description: "Main exit door opened while patient was in proximity. Motion detected moving toward entrance.",
    triggeredAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    triggeredLocation: { lat: 37.7749, lng: -122.4194 },
    escalationLevel: 3,
    escalationHistory: [
      {
        level: 1,
        triggeredAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
        action: "Sensor Triggered",
        recipient: "System",
      },
      {
        level: 2,
        triggeredAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
        action: "Nurse Station Alert",
        recipient: "Dashboard",
      },
      {
        level: 3,
        triggeredAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
        action: "Caregiver Contact",
        recipient: "Dr. Chen",
      },
    ],
  },
  {
    id: "9922",
    patientId: "1",
    type: "zone_exit",
    severity: "high",
    status: "resolved",
    title: "Zone Boundary Alert",
    description: "Patient approached edge of safe zone perimeter.",
    triggeredAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    triggeredLocation: { lat: 37.7751, lng: -122.4192 },
    escalationLevel: 1,
    escalationHistory: [
      {
        level: 1,
        triggeredAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        action: "Alert Triggered",
        recipient: "Primary Caregiver",
      },
    ],
    resolvedAt: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    resolvedBy: "Jane Doe",
    resolution: "Patient returned to safe zone",
  },
]

export const demoActivities: ActivityEvent[] = [
  {
    id: "1",
    patientId: "1",
    type: "zone_enter",
    title: "Entered Master Bedroom",
    description: "Patient moved to master bedroom area",
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    zone: "Master Bedroom",
  },
  {
    id: "2",
    patientId: "1",
    type: "check_in",
    title: "Medication Reminder",
    description: "Evening medication reminder sent",
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    patientId: "1",
    type: "zone_exit",
    title: "Left Living Room",
    description: "Patient left living room area",
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    zone: "Living Room",
  },
  {
    id: "4",
    patientId: "1",
    type: "zone_enter",
    title: "Entered Kitchen",
    description: "Patient moved to kitchen area",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    zone: "Kitchen",
  },
]

export const allPatients: Patient[] = [
  demoPatient,
  {
    ...demoPatient,
    id: "2",
    firstName: "James",
    lastName: "Sullivan",
    photo: "/placeholder.svg?height=120&width=120",
    dateOfBirth: "1942-05-23",
    status: "advisory",
    device: {
      ...demoPatient.device,
      id: "SW-9929-XB",
      batteryLevel: 45,
    },
  },
  {
    ...demoPatient,
    id: "3",
    firstName: "Margaret",
    lastName: "Thompson",
    photo: "/placeholder.svg?height=120&width=120",
    dateOfBirth: "1948-11-08",
    status: "safe",
    device: {
      ...demoPatient.device,
      id: "SW-9930-XC",
      batteryLevel: 92,
    },
  },
]
